language: node_js

node_js:
  - "12"

script: npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: dist
  target-branch: gh-pages
  fqdn: flash.mokeedev.com
  keep-history: true
  on:
    branch: v2
